# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 17:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160422_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
