# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-02 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20160506_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='game',
        ),
        migrations.RemoveField(
            model_name='webhooklog',
            name='webhook',
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
        migrations.DeleteModel(
            name='WebhookLog',
        ),
    ]
