# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20160602_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='games.Phase'),
        ),
    ]
