# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_run_phase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together=set([('name', 'period', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set([('name', 'period', 'role')]),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('name', 'game')]),
        ),
    ]
