# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20160901_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
