# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20160902_0058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together=set([('name', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('name', 'world')]),
        ),
        migrations.AlterUniqueTogether(
            name='run',
            unique_together=set([('name', 'game')]),
        ),
        migrations.AlterUniqueTogether(
            name='runuser',
            unique_together=set([('user', 'run')]),
        ),
        migrations.AlterUniqueTogether(
            name='scenario',
            unique_together=set([('name', 'round')]),
        ),
        migrations.AlterUniqueTogether(
            name='world',
            unique_together=set([('name', 'run')]),
        ),
    ]
