# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20160902_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together=set([]),
        ),
    ]
