# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20160902_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='period',
            unique_together=set([('scenario', 'order')]),
        ),
    ]
