# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 12:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20160906_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
