# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-30 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20160930_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ('created',), 'verbose_name': 'world', 'verbose_name_plural': 'worlds'},
        ),
    ]
