# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20161002_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='runuser',
            name='facilitate_game',
            field=models.ForeignKey(help_text='Applies only to facilators', null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
