# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_runuser_facilitate_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runuser',
            name='facilitate_game',
        ),
    ]
