# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-04 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_auto_20161004_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('game', 'order'), 'verbose_name': 'phase', 'verbose_name_plural': 'phases'},
        ),
        migrations.AlterField(
            model_name='phase',
            name='order',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
