# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20161005_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('pk',), 'verbose_name': 'scenario', 'verbose_name_plural': 'scenarios'},
        ),
    ]
