# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-06 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_auto_20161006_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('created',), 'verbose_name': 'scenario', 'verbose_name_plural': 'scenarios'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ('created',), 'verbose_name': 'world', 'verbose_name_plural': 'worlds'},
        ),
    ]
