# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20170130_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='creator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='games.RunUser'),
        ),
    ]
