# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_auto_20170210_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='games.Round'),
        ),
    ]
