# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-17 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20170313_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runuser',
            old_name='facilitator',
            new_name='leader',
        ),
    ]
