# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-20 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20170317_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='run',
            name='start_date',
        ),
    ]
