# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20170320_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='current_period',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='last_period',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='player_periods',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='seed_periods',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='total_periods',
        ),
    ]
