# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-29 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20170329_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='round',
            name='world',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='round',
        ),
        migrations.AddField(
            model_name='scenario',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='games.World'),
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
