# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_auto_20170329_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
