# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-12 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_auto_20170511_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
