# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-17 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20170512_1650'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='run',
            unique_together=set([]),
        ),
    ]
