# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20170717_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
