# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_auto_20170808_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('name',), 'verbose_name': 'decision', 'verbose_name_plural': 'decisions'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('name',), 'verbose_name': 'result', 'verbose_name_plural': 'results'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('created',), 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('-created',), 'verbose_name': 'run', 'verbose_name_plural': 'runs'},
        ),
        migrations.AlterModelOptions(
            name='runuser',
            options={'ordering': ('run', 'user', 'created'), 'verbose_name': 'run user', 'verbose_name_plural': 'run users'},
        ),
    ]
