# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_auto_20170914_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ('pk',), 'verbose_name': 'decision', 'verbose_name_plural': 'decisions'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('pk',), 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ('pk',), 'verbose_name': 'period', 'verbose_name_plural': 'periods'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ('pk',), 'verbose_name': 'phase', 'verbose_name_plural': 'phases'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('pk',), 'verbose_name': 'result', 'verbose_name_plural': 'results'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'ordering': ('pk',), 'verbose_name': 'run', 'verbose_name_plural': 'runs'},
        ),
        migrations.AlterModelOptions(
            name='runuser',
            options={'ordering': ('pk',), 'verbose_name': 'run user', 'verbose_name_plural': 'run users'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'ordering': ('pk',), 'verbose_name': 'scenario', 'verbose_name_plural': 'scenarios'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'ordering': ('pk',), 'verbose_name': 'world', 'verbose_name_plural': 'worlds'},
        ),
    ]
