# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_auto_20180703_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
