# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 17:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_phase_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
