# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_game_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='decision',
            unique_together=set([('name', 'period', 'role')]),
        ),
    ]
