# Generated by Django 2.2.17 on 2020-11-18 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_message_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('pk',), 'verbose_name': 'Chat Message'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('pk',), 'verbose_name': 'Chat Room'},
        ),
    ]
