# Generated by Django 2.2.16 on 2020-11-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_auto_20201115_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('pk',)},
        ),
    ]
