# Generated by Django 2.2.12 on 2020-06-04 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, help_text="Events to receive, should be namespaced with periods 'user.*', 'blackjack.*', etc.", max_length=200)),
                ('url', models.URLField(db_index=True, help_text='URL to POST event', max_length=255)),
                ('connected', models.BooleanField(db_index=True, default=False, help_text='Has sent successful hooks in the past')),
                ('erroring', models.BooleanField(db_index=True, default=False, help_text='Currently erroring out')),
                ('last_error', models.DateTimeField(blank=True, help_text='Last webhook POST that errored', null=True)),
                ('last_error_status', models.IntegerField(blank=True, null=True)),
                ('last_error_content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
