# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_auto_20160322_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roster.World'),
        ),
    ]
