# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_phase_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_rounds', to='roster.Phase'),
        ),
        migrations.AddField(
            model_name='world',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='roster.Phase'),
        ),
    ]
