# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 20:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0002_auto_20160325_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='simpl.Scenario')),
            ],
            options={
                'verbose_name_plural': 'periods',
                'verbose_name': 'period',
            },
        ),
        migrations.RemoveField(
            model_name='action',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='decision',
            name='action',
        ),
        migrations.RemoveField(
            model_name='result',
            name='action',
        ),
        migrations.DeleteModel(
            name='Action',
        ),
        migrations.AddField(
            model_name='decision',
            name='period',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='simpl.Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='period',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simpl.Period'),
            preserve_default=False,
        ),
    ]
