# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0002_auto_20160314_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
