# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0003_auto_20160314_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'action', 'verbose_name_plural': 'actions'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'verbose_name': 'phase', 'verbose_name_plural': 'phases'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'verbose_name': 'round', 'verbose_name_plural': 'rounds'},
        ),
        migrations.AlterModelOptions(
            name='run',
            options={'verbose_name': 'run', 'verbose_name_plural': 'runs'},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'verbose_name': 'scenario', 'verbose_name_plural': 'scenarios'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'verbose_name': 'webhook', 'verbose_name_plural': 'webhooks'},
        ),
        migrations.AlterModelOptions(
            name='webhooklog',
            options={'verbose_name': 'webhook log', 'verbose_name_plural': 'webhook logs'},
        ),
        migrations.AlterModelOptions(
            name='world',
            options={'verbose_name': 'world', 'verbose_name_plural': 'worlds'},
        ),
    ]
