# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0003_auto_20160407_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='world',
        ),
    ]
