# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0004_remove_role_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='simpl.Game'),
        ),
    ]
