# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0005_auto_20160325_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='position',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='round',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='round',
            name='phase',
        ),
    ]
