# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0005_role_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='number',
        ),
    ]
