# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_decision_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'verbose_name': 'decision', 'verbose_name_plural': 'decisions'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'result', 'verbose_name_plural': 'results'},
        ),
        migrations.AlterField(
            model_name='action',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='roster.Scenario'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='roster.Action'),
        ),
        migrations.AlterField(
            model_name='game',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phase',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='roster.Game'),
        ),
        migrations.AlterField(
            model_name='result',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='roster.Action'),
        ),
        migrations.AlterField(
            model_name='role',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roster.World'),
        ),
        migrations.AlterField(
            model_name='round',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='roster.Phase'),
        ),
        migrations.AlterField(
            model_name='round',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='roster.World'),
        ),
        migrations.AlterField(
            model_name='run',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='roster.Game'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='roster.Round'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='roster.Game'),
        ),
        migrations.AlterField(
            model_name='webhooklog',
            name='webhook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooklogs', to='roster.Webhook'),
        ),
        migrations.AlterField(
            model_name='world',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='roster.Run'),
        ),
    ]
