# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0006_auto_20160325_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
