# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0007_role_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='user',
            new_name='creator_user',
        ),
    ]
