# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0007_auto_20160420_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
