# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0008_auto_20160325_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='current_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_period_scenarios', to='simpl.Period'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='last_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_period_scenarios', to='simpl.Period'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='player_periods',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='seed_periods',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='total_periods',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
