# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0009_auto_20160325_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='game',
            name='superusers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
