# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0010_auto_20160328_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='state',
            new_name='data',
        ),
    ]
