# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0011_auto_20160328_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='run',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
