# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0012_auto_20160328_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='position',
            new_name='order',
        ),
    ]
