# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpl', '0013_auto_20160328_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
